### PR TITLE
Feat : Update prettier for TS 4.9

### PR DESCRIPTION
**Pull request by taiwabisabi**
- [x] update prettier to handle TS 4.9

### CODE REVIEW

**Comment by ratierd** [comment]
@ayusharma, @byara Can we merge this ? It's blocking for projects using typescript 4.9 and the new `satisfies` operator

**Review by ratierd — APPROVED** [review]

**Review by byara — APPROVED** [review]

**Comment by nkeil** [comment]
When can we expect an official release for this fix?

**Comment by moretti** [comment]
I'm also looking for this change. 

With the latest version of yarn, you can patch the package on `.yarnrc` using [`packageExtensions`](https://yarnpkg.com/configuration/yarnrc#packageExtensions)

```.yml
packageExtensions:
  '@trivago/prettier-plugin-sort-imports@*':
    dependencies:
      prettier: '^2.8.2'
```

**Comment by ayusharma** [comment]
Released in [v4.1.0](https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v4.1.0). I appreciate your patience. ❤️

**Pull request merged**
