### PR TITLE
Try fix install not working with Prettier 2.3

### PR DESCRIPTION
**Pull request by scmx**
This PR tries to fix https://github.com/trivago/prettier-plugin-sort-imports/issues/61

Cherry-picked commit from https://github.com/trivago/prettier-plugin-sort-imports/pull/63 from @JamesGelok to fix `tsc` not working.

### CODE REVIEW

**Comment by JulienKode** [comment]
Any update regarding the merge of this pull request ?

**Comment by hanneswidrig** [comment]
Is there anything that can be done to accelerate support for Prettier 2.3? I would like to use this library but the lack of support for newer versions of Prettier at the moment concerns me as I don't want to rely on a weakly supported plugin as Prettier sees improvements.

**Review by byara — APPROVED** [review]
LGTM!

**Comment by byara** [comment]
The fix is published at [v2.0.3](https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v2.0.3)

**Pull request merged**
