### PR TITLE
Support passing babel plugin configuration in JSON

### PR DESCRIPTION
**Pull request by saaryab**
This PR is a fix for this issue:
https://github.com/trivago/prettier-plugin-sort-imports/issues/86

Prettier does not allow complex values in the options file, so in order to support experimental Babel plugins with options I added support for JSON strings in the `experimentalBabelParserPluginsList` options array.

Please let me know if you have other ideas of how to support options in these plugins.

### CODE REVIEW

**Comment by saaryab** [comment]
Hi @byara and team - any chance you could let me know if you will be looking into including this (short) PR, or should I switch to working off a fork?
Thanks!

**Comment by saaryab** [comment]
Hi @byara , thanks for taking the time to look into this.
The error you are getting is the reason for the PR - prettier does run time validation and only accepts primitive types in the options array.
To get around that you can add single quotes around the inner array so it's a JSON string and not an object.

```
'["decorators", { "decoratorsBeforeExport": true }]'
```

It's a bit ugly but it's the simplest way to get around prettier's very limiting restrictions.

**Comment by saaryab** [comment]
> * I took a deeper look and gotta admit I like the following structure better, which at least we are not going to have error messages in any IDEs:
> 
> ```
> "experimentalBabelParserPluginsList": ["[\"decorators\", { \"decoratorsBeforeExport\": true }]", "classProperties"]
> ```

No problem. I'll update the README and tests to use that format.


> * Now that we are adding this, we need to remove the legacy decorator that we are adding automatically in `getParserPlugins` in `src/utils/get-parser-plugins.ts`

I can remove it, but do we need to worry about backward compatibility?
Maybe someone is relying on it and they will need to update their prettierrc file after upgrading this package.

**Comment by ayusharma** [comment]
>I can remove it, but do we need to worry about backward compatibility?
> Maybe someone is relying on it and they will need to update their prettierrc file after upgrading this package. 

Hi @saaryab, I am planning to release this change in the next major version which is **3.x.x** to ensure backward compatibiltiy. Could you please change the target branch of this PR to `v3.x`.

**Comment by saaryab** [comment]
Sounds good - I'll remove the old decorators plugin soon.

**Pull request merged**
