### PR TITLE
version 5

### PR DESCRIPTION
**Pull request by byara**
CHANGELOG: 
- Type imports [#153](https://github.com/trivago/prettier-plugin-sort-imports/pull/153) by [Xenfo](https://github.com/broofa)
- Svelte support [#310](https://github.com/trivago/prettier-plugin-sort-imports/pull/310) by [canarddemagret](https://github.com/canarddemagret)
- Side effect import support [#320](https://github.com/trivago/prettier-plugin-sort-imports/pull/320) by [blutorange](https://github.com/blutorange) and [vladislavarsenev](https://github.com/vladislavarsenev)
- Fixed dollar sign group replace in Vue [#283](https://github.com/trivago/prettier-plugin-sort-imports/pull/283) by [adamDilger](https://github.com/adamDilger)
- Support `importOrderImportAttributesKeyword` [#273](https://github.com/trivago/prettier-plugin-sort-imports/pull/273) by [chentsulin](https://github.com/chentsulin)

### CODE REVIEW

**Comment by quanglam2807** [comment]
Please release v5!!

**Review by quanglam2807 — APPROVED** [review]

**Comment by PupoSDC** [comment]
When is this coming?

**Review by PupoSDC — APPROVED** [review]

**Comment by kabirsky** [comment]
Seems like easy PR, you may at least propagate it with pre-release tag, so who want type import sort will explicitly move onto pre-release, the rest will not even notice

**Comment by PupoSDC** [comment]
Is there a timeline on getting this released? 
We are still pinned to version 4.1.0 to have this working.

**Comment by gyenabubakar** [comment]
Any updates on this? A pre-release would be great whilst we wait...

**Review by ayusharma — APPROVED** [review]

**Review by ayusharma — APPROVED** [review]

**Comment by JBloss1517** [comment]
Looking forward to this being merged to have svelte support 🚀

**Comment by nVitius** [comment]
Been waiting for type imports sorting for almost two years. Very excited to see this finally merged in.

**Pull request merged**
