### PR TITLE
Fix faulty comment replace in removeNodesFromOriginalCode

### LINKED ISSUE #55: Commented imports dupe
File Imports or destructured imports get duped after formatting if they're commented at the beginning of the file.

I have the following config:
```json
{
  "importOrder": [
    "^@k9/(.*)$",
    "^@(.*)$",
    "^[./]"
  ],
  "importOrderSeparation": true,
  "semi": false,
  "singleQuote": true,
  "printWidth": 80
}

```

gif

### PR DESCRIPTION
**Pull request by raineorshine**
Fixes #55

The cause of #55 is that `removeNodesFromOriginalCode` accidentally removes the import from the matching comment if it comes earlier in the source.

I couldn't figure out a way to do this without `new RegExp`. I tried 🙂. I'm not sure if you can constrain the scope of the replace or if it has to replace from all code.

### CODE REVIEW

**Comment by ayusharma** [comment]
Hi, thanks for the PR. I'll get back on it soon. 😃

**Review by byara — APPROVED** [review]
Looks good to me 👍

**Comment by byara** [comment]
Thanks @raineorshine for your contribution!

**Comment by ayusharma** [comment]
Released in v2.0.4 📦

**Comment by ayusharma** [comment]
Hi @raineorshine , Thank you so much for your PR. Please respond to the notification here. https://github.com/trivago/prettier-plugin-sort-imports/discussions/118

**Pull request merged**
