### PR TITLE
Upgrade @babel/traverese to not-vulnerable version

### PR DESCRIPTION
**Pull request by helgefredheim**
According to dependabot there is a vulnerability in @babel/traverse <7.23.2

The vulnerability is fixed in 7.23.2

### CODE REVIEW

**Review by ayhanadem — APPROVED** [review]

**Review by ayhanadem — APPROVED** [review]

**Comment by StavNoyAkur8** [comment]
Duplicate of https://github.com/trivago/prettier-plugin-sort-imports/pull/263 ?

**Comment by helgefredheim** [comment]
> Duplicate of #263 ?

seems so! closing this :)

**Comment by hamidrezahanafi** [comment]
I think your version doesn't have breaking changes @helgefredheim

**Comment by helgefredheim** [comment]
> I think your version doesn't have breaking changes @helgefredheim

Ok, I repoen this then.

**Comment by helgefredheim** [comment]
Closing again, as this now is fixed in another PR.

**Pull request closed without merging**
