### PR TITLE
Move @babel/core to devDependencies

### PR DESCRIPTION
**Pull request by yykamei**
As far as I see, `@babel/core` is only used for testing in this repository.

I think it would be better to move it to `devDependencies` because this plugin users can reduce npm dependencies in their lock files; `@babel/core` has many dependencies, so I will have to bump many dependencies in my `yarn.lock` if they have updates.

I just ran `yarn remove @babel/core` and `yarn add --dev @babel/core`.

What do you think?

### CODE REVIEW

**Comment by LukeSheard** [comment]
This is actually a blocker for this plugin supporting TypeScript 4.9 as the babel deps are so out of date that it causes eslint parsing to fail.

**Comment by DanielPower** [comment]
Related issue: https://github.com/trivago/prettier-plugin-sort-imports/pull/200

**Review by Leomotors — APPROVED** [review]

**Review by byara — APPROVED** [review]

**Comment by ayusharma** [comment]
Released in [v4.1.0](https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v4.1.0). I appreciate your patience. ❤️

**Comment by yykamei** [comment]
Thank you 👍

**Pull request merged**
